// +build !ignore_autogenerated

/*
Copyright © 2021 SonicWall, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicwallNetworkPolicy) DeepCopyInto(out *SonicwallNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make(SonicwallNetworkPolicySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicy.
func (in *SonicwallNetworkPolicy) DeepCopy() *SonicwallNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonicwallNetworkPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicwallNetworkPolicyEgressItem) DeepCopyInto(out *SonicwallNetworkPolicyEgressItem) {
	*out = *in
	if in.ToEndpoints != nil {
		in, out := &in.ToEndpoints, &out.ToEndpoints
		*out = make([]SonicwallNetworkPolicyEndpointSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ToCIDR != nil {
		in, out := &in.ToCIDR, &out.ToCIDR
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ToFQDN != nil {
		in, out := &in.ToFQDN, &out.ToFQDN
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ToPorts != nil {
		in, out := &in.ToPorts, &out.ToPorts
		*out = make([]SonicwallNetworkPolicyPorts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicyEgressItem.
func (in *SonicwallNetworkPolicyEgressItem) DeepCopy() *SonicwallNetworkPolicyEgressItem {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicyEgressItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicwallNetworkPolicyEndpointSelector) DeepCopyInto(out *SonicwallNetworkPolicyEndpointSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicyEndpointSelector.
func (in *SonicwallNetworkPolicyEndpointSelector) DeepCopy() *SonicwallNetworkPolicyEndpointSelector {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicyEndpointSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicwallNetworkPolicyIngressItem) DeepCopyInto(out *SonicwallNetworkPolicyIngressItem) {
	*out = *in
	if in.FromEndpoints != nil {
		in, out := &in.FromEndpoints, &out.FromEndpoints
		*out = make([]SonicwallNetworkPolicyEndpointSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FromCIDR != nil {
		in, out := &in.FromCIDR, &out.FromCIDR
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FromFQDN != nil {
		in, out := &in.FromFQDN, &out.FromFQDN
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FromPorts != nil {
		in, out := &in.FromPorts, &out.FromPorts
		*out = make([]SonicwallNetworkPolicyPorts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicyIngressItem.
func (in *SonicwallNetworkPolicyIngressItem) DeepCopy() *SonicwallNetworkPolicyIngressItem {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicyIngressItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicwallNetworkPolicyList) DeepCopyInto(out *SonicwallNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SonicwallNetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicyList.
func (in *SonicwallNetworkPolicyList) DeepCopy() *SonicwallNetworkPolicyList {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonicwallNetworkPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicwallNetworkPolicyPort) DeepCopyInto(out *SonicwallNetworkPolicyPort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicyPort.
func (in *SonicwallNetworkPolicyPort) DeepCopy() *SonicwallNetworkPolicyPort {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicyPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicwallNetworkPolicyPorts) DeepCopyInto(out *SonicwallNetworkPolicyPorts) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]SonicwallNetworkPolicyPort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicyPorts.
func (in *SonicwallNetworkPolicyPorts) DeepCopy() *SonicwallNetworkPolicyPorts {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicyPorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in SonicwallNetworkPolicySpec) DeepCopyInto(out *SonicwallNetworkPolicySpec) {
	{
		in := &in
		*out = make(SonicwallNetworkPolicySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicySpec.
func (in SonicwallNetworkPolicySpec) DeepCopy() SonicwallNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicySpec)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicwallNetworkPolicySpecItem) DeepCopyInto(out *SonicwallNetworkPolicySpecItem) {
	*out = *in
	in.EndpointSelector.DeepCopyInto(&out.EndpointSelector)
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = make([]SonicwallNetworkPolicyIngressItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]SonicwallNetworkPolicyEgressItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicwallNetworkPolicySpecItem.
func (in *SonicwallNetworkPolicySpecItem) DeepCopy() *SonicwallNetworkPolicySpecItem {
	if in == nil {
		return nil
	}
	out := new(SonicwallNetworkPolicySpecItem)
	in.DeepCopyInto(out)
	return out
}
